# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bartender-6 = {
    pname = "bartender-6";
    version = "6-0-0";
    src = fetchurl {
      url = "https://macbartender.com/B2/updates/6-0-0/Bartender%206.dmg";
      name = "Bartender6.dmg";
      sha256 = "sha256-oJOGgkYRWNNOEMZ8iv+naPTVZxIf3oMb/K4WfvVwsnc=";
    };
  };
  ghostty = {
    pname = "ghostty";
    version = "1.2.1";
    src = fetchurl {
      url = "https://release.files.ghostty.org/1.2.1/Ghostty.dmg";
      sha256 = "sha256-rFXYJxz6UPE8KKhrPLvksLLvxUdlZzvoxLGhIF3hTGM=";
    };
  };
  ghostty-nightly = {
    pname = "ghostty-nightly";
    version = "tip";
    src = fetchurl {
      url = "https://github.com/ghostty-org/ghostty/releases/download/tip/Ghostty.dmg";
      sha256 = "sha256-0h9UuMX/jEKZtBt7LfuiNhye3gm9PPuxkxYz2hUjpNg=";
    };
  };
  helium-linux = {
    pname = "helium-linux";
    version = "0.5.2.1";
    src = fetchFromGitHub {
      owner = "imputnet";
      repo = "helium-linux";
      rev = "0.5.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-SNZgFhObIVeGfG0j4ZMDk+XbBhQPe9U/BIBbjA12s70=";
    };
  };
  helium-macos = {
    pname = "helium-macos";
    version = "0.5.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.5.2.1/helium_0.5.2.1_arm64-macos.dmg";
      sha256 = "sha256-gw5ziIX9oYSZ0HnMgTNpvdILhsoO5aF+2l/KQzPoPHQ=";
    };
  };
  kanata = {
    pname = "kanata";
    version = "25193104aad589e6df4a4ec700750ff8e18d27bd";
    src = fetchFromGitHub {
      owner = "jtroo";
      repo = "kanata";
      rev = "25193104aad589e6df4a4ec700750ff8e18d27bd";
      fetchSubmodules = false;
      sha256 = "sha256-vnz3/GkQm3PE3mA97jLbvVouQot6tOylpdJXRfpSFrA=";
    };
    date = "2025-10-01";
  };
  kanata-vk-agent = {
    pname = "kanata-vk-agent";
    version = "63622d603651edf741c60c465209751e32c91261";
    src = fetchFromGitHub {
      owner = "devsunb";
      repo = "kanata-vk-agent";
      rev = "63622d603651edf741c60c465209751e32c91261";
      fetchSubmodules = false;
      sha256 = "sha256-Yxf24imM9d9z17h6mZaTz2XhlNzgFbRqqKiBAmo/Skg=";
    };
    date = "2025-02-15";
  };
  karabiner-dk = {
    pname = "karabiner-dk";
    version = "6.3.0";
    src = fetchTarball {
      url = "https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/archive/v6.3.0.tar.gz";
      sha256 = "sha256-nLu//qG3RzrEDWvNmSJH7YmgVgiTiYTg5FaliiEtdpo=";
    };
  };
  yabai = {
    pname = "yabai";
    version = "v7.1.15";
    src = fetchFromGitHub {
      owner = "koekeishiya";
      repo = "yabai";
      rev = "v7.1.15";
      fetchSubmodules = false;
      sha256 = "sha256-HvaMPmXNlFVOezqWxqXaAUq8E8O2ZkXMQPwkKXCAOcY=";
    };
  };
  zen = {
    pname = "zen";
    version = "1.16.3b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.16.3b/zen.macos-universal.dmg";
      sha256 = "sha256-mWxTEYS8ClA8qQWVgr09oX3WWAh/xFK+AxkY2p/URFI=";
    };
  };
  zen-twilight = {
    pname = "zen-twilight";
    version = "1.16.3b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/twilight/zen.macos-universal.dmg";
      sha256 = "sha256-lzJYnn7R0mwR2LJezTwgYR2jjGtsuD6pFOnJEegqs04=";
    };
  };
}
