# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bartender-6 = {
    pname = "bartender-6";
    version = "6-0-0";
    src = fetchurl {
      url = "https://macbartender.com/B2/updates/6-0-0/Bartender%206.dmg";
      name = "Bartender6.dmg";
      sha256 = "sha256-oJOGgkYRWNNOEMZ8iv+naPTVZxIf3oMb/K4WfvVwsnc=";
    };
  };
  ghostty = {
    pname = "ghostty";
    version = "1.2.2";
    src = fetchurl {
      url = "https://release.files.ghostty.org/1.2.2/Ghostty.dmg";
      sha256 = "sha256-gSuOOWZUzKKihCGmqEnieJJ8iP4xFeoSQIL536ka454=";
    };
  };
  ghostty-nightly = {
    pname = "ghostty-nightly";
    version = "tip";
    src = fetchurl {
      url = "https://github.com/ghostty-org/ghostty/releases/download/tip/Ghostty.dmg";
      sha256 = "sha256-J4IWcBmRUsxjTHT+7VUGMlGHiCcck2YI2N/jCBnDc5A=";
    };
  };
  helium-linux = {
    pname = "helium-linux";
    version = "0.5.5.1";
    src = fetchFromGitHub {
      owner = "imputnet";
      repo = "helium-linux";
      rev = "0.5.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-SNZgFhObIVeGfG0j4ZMDk+XbBhQPe9U/BIBbjA12s70=";
    };
  };
  helium-macos = {
    pname = "helium-macos";
    version = "0.5.5.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.5.5.1/helium_0.5.5.1_arm64-macos.dmg";
      sha256 = "sha256-QOQEEmUm60Sm197kadhr4Z1/abdsbbQw6Arax8YAIVo=";
    };
  };
  kanata = {
    pname = "kanata";
    version = "26640cacd9a5ea163505e6660d466b0b8a0791e3";
    src = fetchFromGitHub {
      owner = "jtroo";
      repo = "kanata";
      rev = "26640cacd9a5ea163505e6660d466b0b8a0791e3";
      fetchSubmodules = false;
      sha256 = "sha256-aQDeMfkb6wjwQ40wP0XE2JcaOrHArvItVfB6QsmVpuc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-aQDeMfkb6wjwQ40wP0XE2JcaOrHArvItVfB6QsmVpuc=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2025-10-11";
  };
  kanata-vk-agent = {
    pname = "kanata-vk-agent";
    version = "63622d603651edf741c60c465209751e32c91261";
    src = fetchFromGitHub {
      owner = "devsunb";
      repo = "kanata-vk-agent";
      rev = "63622d603651edf741c60c465209751e32c91261";
      fetchSubmodules = false;
      sha256 = "sha256-Yxf24imM9d9z17h6mZaTz2XhlNzgFbRqqKiBAmo/Skg=";
    };
    date = "2025-02-15";
  };
  karabiner-dk = {
    pname = "karabiner-dk";
    version = "v6.4.0";
    src = fetchFromGitHub {
      owner = "pqrs-org";
      repo = "Karabiner-DriverKit-VirtualHIDDevice";
      rev = "v6.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-NlzIb9srGVdYUOAOL8W9UJZVrf5IQOm6TVjm73epemM=";
    };
  };
  yabai = {
    pname = "yabai";
    version = "v7.1.16";
    src = fetchFromGitHub {
      owner = "koekeishiya";
      repo = "yabai";
      rev = "v7.1.16";
      fetchSubmodules = false;
      sha256 = "sha256-WXvM0ub4kJ3rKXynTxmr2Mx+LzJOgmm02CcEx2nsy/A=";
    };
  };
  zen = {
    pname = "zen";
    version = "1.16.4b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.16.4b/zen.macos-universal.dmg";
      sha256 = "sha256-jGOyE26JntBMQBu7w+pwHpKMFCd+lx6SyjapX0KCQUc=";
    };
  };
  zen-twilight = {
    pname = "zen-twilight";
    version = "1.16.4b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/twilight/zen.macos-universal.dmg";
      sha256 = "sha256-DrtQ4ReiHWgL00x1Y9UDg9tVJC6yzH49lkxxbT+h+jM=";
    };
  };
}
