# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  flake-compat = {
    pname = "flake-compat";
    version = "flake-compat";
    src = fetchTarball {
      url = "https://git.lix.systems/lix-project/flake-compat/archive/main.tar.gz";
      sha256 = "sha256-Eg9b/rq/ECYwNwEXs5i9wHyhxNI0JrYx2srdI2uZMaQ=";
    };
    extract = {
      "default.nix" = ./. + "/sha256-Eg9b_rq_ECYwNwEXs5i9wHyhxNI0JrYx2srdI2uZMaQ=/default.nix";
    };
  };
  ghostty = {
    pname = "ghostty";
    version = "1.3.1";
    src = fetchurl {
      url = "https://release.files.ghostty.org/1.3.1/Ghostty.dmg";
      sha256 = "sha256-GM/ysKbO6Q7q2cfTBk6AiiUqQLryFKp1LB7LeTuPX2k=";
    };
  };
  ghostty-nightly = {
    pname = "ghostty-nightly";
    version = "tip";
    src = fetchurl {
      url = "https://github.com/ghostty-org/ghostty/releases/download/tip/ghostty-macos-universal.zip";
      sha256 = "sha256-Q7eI9hEa90Ek/rj8u9dn119MtkvL33gi7zuTtaw+Chg=";
    };
  };
  helium-linux = {
    pname = "helium-linux";
    version = "0.19.2.1";
    src = fetchFromGitHub {
      owner = "imputnet";
      repo = "helium-linux";
      rev = "0.19.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-yr5JIGRdE9t2lFQfN6UVqb39WG85IfcnJD3zQ5dqQCk=";
    };
  };
  helium-macos = {
    pname = "helium-macos";
    version = "0.19.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.19.2.1/helium_0.19.2.1_arm64-macos.dmg";
      sha256 = "sha256-wH2rnBVxz2jPhWs1xtC/IcLPU/d8QyRRYwGOeICU6/E=";
    };
  };
  kanata = {
    pname = "kanata";
    version = "v1.13.0-prerelease-1";
    src = fetchFromGitHub {
      owner = "jtroo";
      repo = "kanata";
      rev = "v1.13.0-prerelease-1";
      fetchSubmodules = false;
      sha256 = "sha256-EDmhgP8P4wZolP9QZDrO0VOODd5c0416ruPNIeftLys=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-EDmhgP8P4wZolP9QZDrO0VOODd5c0416ruPNIeftLys=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  kanata-tray = {
    pname = "kanata-tray";
    version = "v0.8.0";
    src = fetchFromGitHub {
      owner = "rszyma";
      repo = "kanata-tray";
      rev = "v0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-RTLFDB/irtEhEHwarROGmS4jNdRhruU1JKen48ADzZg=";
    };
  };
  kanata-vk-agent = {
    pname = "kanata-vk-agent";
    version = "8ce982af6a308788070c076619554d05375b6521";
    src = fetchgit {
      url = "https://github.com/auscyber/kanata-vk-agent.git";
      rev = "8ce982af6a308788070c076619554d05375b6521";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hLRJcyaBNTl0dSPuoE7owwFqCcSrwqYo9yaF1O4wxk0=";
    };
    date = "2025-11-03";
  };
  karabiner-dk = {
    pname = "karabiner-dk";
    version = "8.6.0";
    src = fetchurl {
      url = "https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/archive/v8.6.0.tar.gz";
      sha256 = "sha256-qmhYDUF22NqVyYo/Pk3PPWy0AzoRjc0OWrBZHyfKIYY=";
    };
  };
  yabai = {
    pname = "yabai";
    version = "v7.1.25";
    src = fetchFromGitHub {
      owner = "koekeishiya";
      repo = "yabai";
      rev = "v7.1.25";
      fetchSubmodules = false;
      sha256 = "sha256-61knfbahxxlJnVZy47347slsjUGiQUJyZh58G97SDkE=";
    };
  };
  zen = {
    pname = "zen";
    version = "1.23.2b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.23.2b/zen.macos-universal.dmg";
      sha256 = "sha256-l1SMgSPTHIEj8JdiG0fmuZzetXqLo8KbeQ3QZRV/HZ4=";
    };
  };
  zen-twilight = {
    pname = "zen-twilight";
    version = "1.23.2b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/twilight-1/zen.macos-universal.dmg";
      sha256 = "sha256-XhAsk3soiZpd742OPmE9K8mwZ2db+F/QXZuadyAKRnE=";
    };
  };
}
